<a href="https://colab.research.google.com/github/keziatanesha/cosong/blob/main/CW_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 9


In [ ]:
import numpy as np
print(np.__version__)

1.19.5


In [ ]:
import time as time
x_list=[i for i in range(100000)]
x=np.array(x_list)

# usual list
st=time.process_time()
x_list=[i+10 for i in x_list]
ed=time.process_time()
print(round(ed-st,5))

# with numpy arrays
st=time.process_time()
x+=10
ed=time.process_time()
print(round(ed-st,5))
# notice that for numpy arrays the operation is much faster!

0.0098
0.00093


In [ ]:
# Numpy arrays can be initialised with multidimensional python lists
x=np.array([1,2,3,4])
print(type(x))
print(x[0],x[1],x[2],x[3])
x[1]=x[2]
print(x)
print(x.shape)

y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y.shape)
print(y.size)
print(y[1,2],y[0,1],y[2,2])

#indexing with negative indices
print(y[1,-1])

<class 'numpy.ndarray'>
1 2 3 4
[1 3 3 4]
(4,)
(3, 3)
9
6 2 9
6


In [ ]:
# slicing
x=np.random.random((4,3))
print(x)

y=x[1:3,1:3]
y[0,0]=0
print(x)
# slice is a view into the original array so modifying it will modify the original array as well

[[0.01451334 0.09635294 0.12840121]
 [0.31708899 0.22942866 0.52095911]
 [0.56002762 0.346785   0.92718556]
 [0.86851292 0.62482821 0.35831934]]
[[0.01451334 0.09635294 0.12840121]
 [0.31708899 0.         0.52095911]
 [0.56002762 0.346785   0.92718556]
 [0.86851292 0.62482821 0.35831934]]


In [ ]:
# difference of integer indexing and slicing

x=np.random.random((5,5))
print(x)
y1=x[:,1]
y2=x[:,1:2]
print(y1,y1.shape)
print(y2,y2.shape)

z1=x[:,1]
z2=x[:,1:2]
print(z1,z1.shape)
print(z2,z2.shape)

print(x[[1,2,3],:].shape)

[[0.49940181 0.4195103  0.38514656 0.71826527 0.6287286 ]
 [0.0993436  0.3491571  0.75061275 0.64501214 0.55672705]
 [0.38488911 0.35915269 0.764277   0.6394005  0.26093407]
 [0.70635164 0.66130632 0.85968882 0.68207478 0.56021635]
 [0.12178269 0.75911695 0.36478372 0.64192495 0.85070041]]
[0.4195103  0.3491571  0.35915269 0.66130632 0.75911695] (5,)
[[0.4195103 ]
 [0.3491571 ]
 [0.35915269]
 [0.66130632]
 [0.75911695]] (5, 1)
[0.4195103  0.3491571  0.35915269 0.66130632 0.75911695] (5,)
[[0.4195103 ]
 [0.3491571 ]
 [0.35915269]
 [0.66130632]
 [0.75911695]] (5, 1)
(3, 5)


In [ ]:
# integer slicing tricks : modify elements in rows or columns on an np array using integer index

x=np.random.random([5,3])

#divide an element for each row by 2
row_ind=[1,0,2,0,1]
r,c=x.shape
print(x[np.arange(r),row_ind])
print(x)
x[np.arange(r),row_ind]/=2
print(x)

#multiply an element from each column by 5
col_ind=[3,4,1]
x[col_ind,np.arange(c)]*=5
print(x)

[0.62428332 0.29308719 0.25345469 0.63514947 0.50053111]
[[0.44043731 0.62428332 0.08114438]
 [0.29308719 0.13159168 0.75352434]
 [0.42663784 0.60002185 0.25345469]
 [0.63514947 0.37200145 0.69349193]
 [0.18385569 0.50053111 0.89945355]]
[[0.44043731 0.31214166 0.08114438]
 [0.1465436  0.13159168 0.75352434]
 [0.42663784 0.60002185 0.12672735]
 [0.31757473 0.37200145 0.69349193]
 [0.18385569 0.25026555 0.89945355]]
[[0.44043731 0.31214166 0.08114438]
 [0.1465436  0.13159168 3.76762168]
 [0.42663784 0.60002185 0.12672735]
 [1.58787367 0.37200145 0.69349193]
 [0.18385569 1.25132776 0.89945355]]


In [ ]:
# numpy with boolean indexing
x=np.random.random([3,3])
sel_ind=x>0.5
print(sel_ind)
print(x[sel_ind])

[[ True  True False]
 [ True  True False]
 [False  True False]]
[0.68172656 0.96413036 0.51887193 0.91725844 0.93999055]


In [ ]:
# some np arrays with particular tyoe of values
x=np.zeros((3,2))
print(x)
y=np.ones((2,2))
print(y)
i=np.eye(2)
print(i)
c=np.full((2,2),3)
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[3 3]
 [3 3]]


In [ ]:
# Numpy Datatypes - allow us to use arrays of multiple datatypes
x=np.array([1,2,3])
print(x.dtype)
y=np.array([1.,2.,3])
print(y.dtype)
z=x+y
print(z.dtype)

int64
float64
float64


In [ ]:
x=np.random.randint(0,9,(1,4))
y=np.random.randint(2,5,(1,4))
print(x+y)
print(np.add(x,y))

print(np.sqrt(x),np.sqrt(y))

[[11  7  4  7]]
[[11  7  4  7]]
[[2.64575131 2.         0.         1.73205081]] [[2.         1.73205081 2.         2.        ]]


In [ ]:
# multiplication of matric using np.dot or np.matmul
# if both arrays in np.dot are multidimensional np.dot returns the product
# sum over the last dimension of the first array and second to last dimension
# of the second array
# note: for complex conjugate dot product use np.vdot

x=np.random.randint(0,9,(4,))
y=np.random.randint(0,9,(4,))

print(x.shape,y.shape)
print(x.dot(y.T))
print(np.dot(x,y.T))
print(np.matmul(x,y))

x_f=np.random.randint(0,9,(1,4))
y_f=np.random.randint(0,9,(4,1))

print(x.shape,y.shape)
print(x_f.dot(y_f))
print(np.dot(x_f,y_f))
print(np.matmul(x_f,y_f))

w=np.random.randint(0,9,(3,4))
z=np.random.randint(0,9,(4,3))

print(w.dot(z))
print(np.dot(w,z))
print(np.matmul(w,z))


(4,) (4,)
57
57
57
(4,) (4,)
[[61]]
[[61]]
[[61]]
[[54 35 47]
 [49 27 51]
 [94 40 80]]
[[54 35 47]
 [49 27 51]
 [94 40 80]]
[[54 35 47]
 [49 27 51]
 [94 40 80]]


In [ ]:
x=np.random.randint(0,9,(3,4,2))

print('x is :',x)
print('sum of x is:',np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
print(np.sum(x,axis=2))

x is : [[[3 5]
  [8 6]
  [6 7]
  [3 4]]

 [[0 3]
  [7 5]
  [8 3]
  [8 0]]

 [[7 4]
  [3 4]
  [6 1]
  [6 4]]]
sum of x is: 111
[[10 12]
 [18 15]
 [20 11]
 [17  8]]
[[20 22]
 [23 11]
 [22 13]]
[[ 8 14 13  7]
 [ 3 12 11  8]
 [11  7  7 10]]


In [ ]:
x=np.random.randint(0,9,(3,4,2))
print('x is :',x)
print('max of x is:',np.max(x))
print(np.max(x,axis=0))
print(np.max(x,axis=1))
print(np.max(x,axis=2))


x is : [[[1 1]
  [5 4]
  [8 4]
  [7 8]]

 [[6 1]
  [6 0]
  [4 2]
  [5 2]]

 [[4 3]
  [5 5]
  [4 4]
  [3 1]]]
max of x is: 8
[[6 3]
 [6 5]
 [8 4]
 [7 8]]
[[8 8]
 [6 2]
 [5 5]]
[[1 5 8 8]
 [6 6 4 5]
 [4 5 4 3]]


In [ ]:
x=np.random.randint(0,9,(2,2))
y=np.random.randint(0,9,(2,2))
print(x)
print(y)

np.copyto(x,y) #copy y to x
print(x)
print(y)

[[3 6]
 [3 6]]
[[4 4]
 [7 0]]
[[4 4]
 [7 0]]
[[4 4]
 [7 0]]


In [ ]:
# Reshape an array using np.reshape. size of the original array and the reshaped array should be the same. 
# can check using np.ndarray.size
x=np.random.randint(0,9,(4,3))
y=np.reshape(x,(2,6))
print(x)
print(y)

print(np.ravel(x,order='C'))

v=x.flat
print(v[6])

u=x.flatten()
print(u)

[[8 2 0]
 [7 2 0]
 [0 4 6]
 [0 7 5]]
[[8 2 0 7 2 0]
 [0 4 6 0 7 5]]
[8 2 0 7 2 0 0 4 6 0 7 5]
0
[8 2 0 7 2 0 0 4 6 0 7 5]


In [ ]:
# transposition or moving dimensions
v=np.random.randint(0,9,(1,4))
print(v,v.T)
x=np.random.randint(0,9,(2,3))
print(x)
print(x.T)

z=np.zeros((2,3,4))
print(z.shape)
print(np.moveaxis(z,0,1).shape)
print(np.moveaxis(z,0,2).shape)

w=np.ones((5,3,4))
print(w.shape)
print(np.swapaxes(w,0,2).shape)

print(np.transpose(w, axes=(2,1,0)).shape)
print(np.transpose(w,axes=(0,1,2)).shape)

[[0 3 4 3]] [[0]
 [3]
 [4]
 [3]]
[[3 0 8]
 [2 8 0]]
[[3 2]
 [0 8]
 [8 0]]
(2, 3, 4)
(3, 2, 4)
(3, 4, 2)
(5, 3, 4)
(4, 3, 5)
(4, 3, 5)
(5, 3, 4)


In [ ]:
# Numpy Broadcasting
# Broadcasting is a tool in numpy which allows for operation on numoy arrays without the need for looping over all the elements of numpy array
import numpy as np

x=np.ones((1,2,3))
y=0.5*np.ones((3))

print(x*y,(x*y).shape)

x=np.ones((1,2,3))
y=0.5*np.ones((5,1,3))

print(x*y,(x*y).shape)

[[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] (1, 2, 3)
[[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] (5, 2, 3)


In [ ]:
import matplotlib.pyplot as plt
